### ISSUE TITLE
Menu not working (overlapping)

### ISSUE THREAD

**Issue by agucova** [digitalcraftsman/hugo-strata-theme#41]
Since installing, the menu has been showing like this, while on a desktop (compact version works):
<img width="250" alt="whatt" src="https://user-images.githubusercontent.com/4694408/35757329-49962570-084d-11e8-8bc6-c34cba59eb9f.png">
Also, I tried to set the order using weight, but the order keeps messing up, any ideas?

**Comment by agucova** [comment]
Fixed. It seemed to be caused by an oversized avatar, which gives me an egg shape.

**Comment by CodeWritingCow** [comment]
I have a similar problem on smaller screen sizes. (ex. 630 x 1165 and 650x1552). Compact version and full-screen desktop vesions work.

![screenshot](https://user-images.githubusercontent.com/7751862/39149121-1fdf7008-470c-11e8-8766-561c022e35de.png)

**Comment by GemKosan** [comment]
Since the footer has position: fixed, it overlaps the sidebar for viewport heights less than 680 px.
And this is with only 3 sidebar menu items. 

<img width="1138" alt="Screen Shot 2020-04-05 at 3 33 32 PM" src="https://user-images.githubusercontent.com/51011468/78701937-71237780-78cd-11ea-9de4-61a1543f2226.png">
